/*=============================================================================
|	Source code:   main.c
|	Author:   Sean Quinn
|	Student ID: 1203714
|	Assignment:   Program #4 "Poker" 
|
|	Course: COP 4338 - Advanced Programming
|	Section: U04
|	Instructor: William Feild
|	Due Date:   Feb 21, 2017
|
|	I hereby certify that this collective work is my own
|	and none of it is the work of any other person or entity.
|	_______________________________________[Signature]
|
|	Language:   C
|	Compile/Run: type "make" in directory
|			cat Makefile for options	
|			or gcc -o poker main.c poker.h poker.c
|		to run: ./poker followed by two integer arguments
|			the first specifies the number of players 
|			and must be an integer 1-7. The second
|			specifies the number of cards per hand
|			and is fixed at 5 for this game. Ex:
|			$ ./poker 5 5	
|
|   +--------------------------------------------------------------------------
|
|   Description: Simulates a deck of cards. Generates a 52-card deck 
|	and a shuffled version of that deck. Deals five cards to each of a
|	user-specified number of players, from 1 to 7. Prints the resulting
|	dealt hands and evaluates them, displaying the highest-ranked hand
|	as the winner. A test function tests pre-made hands to ensure that
|	all combinations are properly evaluated.
|
|	Input: Accepts 2 command-line arguments, the number of cards per hand
|		and the number of hands dealt. The former is a sham, as the user
|		input is ignored and the number is set at 5.
|
|	Output: Prints the original deck, the shuffled deck, and each 
|		hand dealt. Displays the winning hand. Displays rankings of 
|		pre-set hands.
|
|	Process: A card is represented by a structure that contains an ID
|		number for each card along with integer and string values 
|		that represent the card's rank and suit. A deck is an
|		array of 52 cards that is generated by a counter loop.
|		The counter value becomes the ID of each card, and the ID
|		determines the rank value, counting upward from 1 (ace) to
|		13 (king). Each division of 13 values becomes a suit, 
|		assigned alphabetically.
|
|   	Required Features Not Included:
|		3- shuffle function is created but I can't verify 
|		that it works as expected because I can't get passed
|		arrays to work
|		2- does not deal hands
|		1- does not rank hands 
|
|   	Known Bugs:
|		- not compiling due to "expected ) before numeric
|		constant" error. Can't find an unbalanced parenthesis,
|		think it's something other than what seems obvious
|		- creating a deck in a function and getting it passed
|		back to main...it's not happening
|
|   *========================================================================*/ 
#ifndef POKER
#define POKER "poker.h"
#endif
#include POKER 

int main(int argc, char *argv[]){
	int num_hands;
	int cph; 

	srand(time(NULL));

/*
	srand(CARD_INIT);	
*/
	Deck original_deck;
	Deck shuffled_deck;
	Card *p_orig_deck;
	p_orig_deck = original_deck;

	/* extract & validate arguments */

	if(validate_num_args(argc) == FALSE){
		printf("%s\n", "Exiting: Try again.");
		return FALSE;
	}
	if (validate(atoi(*++argv), atoi(*++argv)) == FALSE){
		printf("%s\n", "Exiting: Try again.");
		return FALSE;
	}
	cph = atoi(*argv);
	num_hands = atoi(*--argv);

/*	
	Card allHands[num_hands][cph];
*/
	Hand allCards;
	Hand *p_Hand;
	Hand allHands[num_hands];
	Hand *p_Game;

	p_Hand = allHands;


	/* create deck */
	p_orig_deck = create_deck(original_deck);
	
	printf("%s\n", "Original deck");
	display_deck(original_deck);

	/* shuffle deck */
	Card *p_shuffled;

	p_shuffled = create_deck(original_deck); 
	p_shuffled = shuffled_deck;
	p_shuffled = shuffle_deck(original_deck); 

	printf("%s\n", "\nShuffled deck");
	display_deck(p_shuffled);	

	/* deal hands */
	p_Hand = dealHands(num_hands, p_shuffled, allHands); 	

	display_all_hands(num_hands,  allHands);
	printf("%s ", "The winning hand is number");
	printf("%d\n",  get_Winner(num_hands, allHands));


	return 0;
}
